# load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_library", "core_resource")

# core_resource(
#     name = "core_resource",
#     src = ":Core/src/Castle.Core/DynamicProxy/DynProxy.snk",
#     identifier = "Castle.Core.DynamicProxy.DynProxy.snk",
# )

# core_library(
#     name = "Castle.Core.dll",
#     srcs = glob(["Core/src/Castle.Core/**/*.cs"]),
#     defines = [
#     ],
#     keyfile = ":Core/buildscripts/CastleKey.snk",
#     visibility = ["//visibility:public"],
#     deps = [
#         "@io_bazel_rules_dotnet//dotnet/stdlib.core:libraryset",
#     ],
# )
