load("@io_bazel_rules_dotnet//dotnet/private:rules/nuget.bzl", "nuget_package")

def repositories_nugets():
    ### Generated by the tool
    nuget_package(
        name = "microsoft.extensions.filesystemglobbing",
        package = "microsoft.extensions.filesystemglobbing",
        version = "3.1.3",
        sha256 = "15ff566cbf79a964269711cb4b1000187ce9bd18a5292363ca55d00ff91a28a5",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
        },
        net_lib = {
            "net461": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net462": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net47": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net471": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net472": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net48": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
        },
        mono_lib = "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netcoreapp3.1": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
        },
        net_files = {
            "net461": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net462": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net47": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net471": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net472": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net48": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netstandard2.0": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netstandard2.1": [
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
                "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
        },
        mono_files = [
            "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
        ],
    )
    nuget_package(
        name = "newtonsoft.json",
        package = "newtonsoft.json",
        version = "9.0.1",
        sha256 = "998081ae052120917346e2cb57d488888147a2fcdf47c52ea9f83a7b4f049e55",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netcoreapp2.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netcoreapp3.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netcoreapp3.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
        },
        net_lib = {
            "net45": "lib/net45/Newtonsoft.Json.dll",
            "net451": "lib/net45/Newtonsoft.Json.dll",
            "net452": "lib/net45/Newtonsoft.Json.dll",
            "net46": "lib/net45/Newtonsoft.Json.dll",
            "net461": "lib/net45/Newtonsoft.Json.dll",
            "net462": "lib/net45/Newtonsoft.Json.dll",
            "net47": "lib/net45/Newtonsoft.Json.dll",
            "net471": "lib/net45/Newtonsoft.Json.dll",
            "net472": "lib/net45/Newtonsoft.Json.dll",
            "net48": "lib/net45/Newtonsoft.Json.dll",
            "netstandard1.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.2": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.3": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.4": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.5": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.6": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard2.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard2.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
        },
        mono_lib = "lib/netstandard1.0/Newtonsoft.Json.dll",
        mono_deps = [
            "@io_bazel_rules_dotnet//dotnet/stdlib:microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.collections.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.diagnostics.debug.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.dynamic.runtime.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.globalization.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.io.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.linq.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.linq.expressions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.objectmodel.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.reflection.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.reflection.extensions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.resources.resourcemanager.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.extensions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.serialization.primitives.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.text.encoding.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.text.encoding.extensions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.text.regularexpressions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.threading.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.threading.tasks.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.xml.readerwriter.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.xml.xdocument.dll",
        ],
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netcoreapp2.1": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netcoreapp3.0": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netcoreapp3.1": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
        },
        net_files = {
            "net45": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net451": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net452": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net46": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net461": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net462": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net47": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net471": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net472": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "net48": [
                "lib/net45/Newtonsoft.Json.dll",
                "lib/net45/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.0": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.1": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.2": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.3": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.4": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.5": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard1.6": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard2.0": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
            "netstandard2.1": [
                "lib/netstandard1.0/Newtonsoft.Json.dll",
                "lib/netstandard1.0/Newtonsoft.Json.xml",
                "tools/install.ps1",
            ],
        },
        mono_files = [
            "lib/netstandard1.0/Newtonsoft.Json.dll",
            "lib/netstandard1.0/Newtonsoft.Json.xml",
            "tools/install.ps1",
        ],
    )
    nuget_package(
        name = "system.runtime.interopservices.runtimeinformation",
        package = "system.runtime.interopservices.runtimeinformation",
        version = "4.0.0",
        sha256 = "e63e776a66fbe80dd23e21370749654f65cfc74e7cf82804ece5cbe1b2da953e",
        core_lib = {
            "netcoreapp2.0": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netcoreapp2.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netcoreapp3.0": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netcoreapp3.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
        },
        net_lib = {
            "net45": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net451": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net452": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net46": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net461": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net462": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net47": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net471": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net472": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net48": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.2": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.3": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.4": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.5": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.6": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard2.0": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard2.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
        },
        mono_lib = "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
        core_deps = {
            "netcoreapp2.0": [
                "@microsoft.netcore.platforms//:netcoreapp2.0_core",
                "@runtime.native.system//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
                "@microsoft.netcore.platforms//:netcoreapp2.1_core",
                "@runtime.native.system//:netcoreapp2.1_core",
            ],
            "netcoreapp3.0": [
                "@microsoft.netcore.platforms//:netcoreapp3.0_core",
                "@runtime.native.system//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
                "@microsoft.netcore.platforms//:netcoreapp3.1_core",
                "@runtime.native.system//:netcoreapp3.1_core",
            ],
        },
        net_deps = {
            "netstandard1.1": [
                "@microsoft.netcore.platforms//:netstandard1.1_net",
                "@runtime.native.system//:netstandard1.1_net",
            ],
            "netstandard1.2": [
                "@microsoft.netcore.platforms//:netstandard1.2_net",
                "@runtime.native.system//:netstandard1.2_net",
            ],
            "netstandard1.3": [
                "@microsoft.netcore.platforms//:netstandard1.3_net",
                "@runtime.native.system//:netstandard1.3_net",
            ],
            "netstandard1.4": [
                "@microsoft.netcore.platforms//:netstandard1.4_net",
                "@runtime.native.system//:netstandard1.4_net",
            ],
            "netstandard1.5": [
                "@microsoft.netcore.platforms//:netstandard1.5_net",
                "@runtime.native.system//:netstandard1.5_net",
            ],
            "netstandard1.6": [
                "@microsoft.netcore.platforms//:netstandard1.6_net",
                "@runtime.native.system//:netstandard1.6_net",
            ],
            "netstandard2.0": [
                "@microsoft.netcore.platforms//:netstandard2.0_net",
                "@runtime.native.system//:netstandard2.0_net",
            ],
            "netstandard2.1": [
                "@microsoft.netcore.platforms//:netstandard2.1_net",
                "@runtime.native.system//:netstandard2.1_net",
            ],
        },
        mono_deps = [
            "@microsoft.netcore.platforms//:mono",
            "@runtime.native.system//:mono",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.reflection.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.resources.resourcemanager.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.interopservices.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.threading.dll",
        ],
        net_files = {
            "net45": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net451": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net452": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net46": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net461": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net462": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net47": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net471": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net472": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net48": [
                "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.dependencymodel",
        package = "microsoft.extensions.dependencymodel",
        version = "3.1.3",
        sha256 = "e2ef26cd9c49f82084e9c8a64082478253fad280fa0c736af4cb94bf5315d428",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
        },
        net_lib = {
            "net451": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net452": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net46": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net461": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net462": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net47": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net471": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net472": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net48": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.3": "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.4": "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.5": "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.6": "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
        },
        mono_lib = "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
        net_deps = {
            "net451": [
                "@newtonsoft.json//:net451_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net451_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net452": [
                "@newtonsoft.json//:net452_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net452_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net46": [
                "@newtonsoft.json//:net46_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net46_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net461": [
                "@newtonsoft.json//:net461_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net462": [
                "@newtonsoft.json//:net462_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net47": [
                "@newtonsoft.json//:net47_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net471": [
                "@newtonsoft.json//:net471_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net472": [
                "@newtonsoft.json//:net472_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "net48": [
                "@newtonsoft.json//:net48_net",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net48_system.runtime.interopservices.runtimeinformation.dll",
            ],
            "netstandard1.3": [
                "@newtonsoft.json//:netstandard1.3_net",
            ],
            "netstandard1.4": [
                "@newtonsoft.json//:netstandard1.4_net",
            ],
            "netstandard1.5": [
                "@newtonsoft.json//:netstandard1.5_net",
            ],
            "netstandard1.6": [
                "@newtonsoft.json//:netstandard1.6_net",
            ],
        },
        mono_deps = [
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.text.json.dll",
        ],
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netcoreapp3.1": [
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
        },
        net_files = {
            "net451": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net452": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net46": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net461": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net462": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net47": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net471": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net472": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net48": [
                "lib/net451/Microsoft.Extensions.DependencyModel.dll",
                "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.3": [
                "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.4": [
                "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.5": [
                "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.6": [
                "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard2.0": [
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard2.1": [
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
                "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
        },
        mono_files = [
            "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
        ],
    )
    nuget_package(
        name = "microsoft.extensions.primitives",
        package = "microsoft.extensions.primitives",
        version = "3.1.3",
        sha256 = "7b77cdb2f39328637eb66bf0982c07badc01c655c9f14e7185cc494b455d154b",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp3.1": "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.dll",
        },
        net_lib = {
            "net461": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net462": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net47": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net471": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net472": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net48": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
        },
        mono_lib = "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.dll",
        net_deps = {
            "net461": [
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.memory.dll",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.runtime.compilerservices.unsafe.dll",
            ],
            "net462": [
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.memory.dll",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.runtime.compilerservices.unsafe.dll",
            ],
            "net47": [
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_system.memory.dll",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_system.runtime.compilerservices.unsafe.dll",
            ],
            "net471": [
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_system.memory.dll",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_system.runtime.compilerservices.unsafe.dll",
            ],
            "net472": [
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_system.memory.dll",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_system.runtime.compilerservices.unsafe.dll",
            ],
            "net48": [
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net48_system.memory.dll",
                "@io_bazel_rules_dotnet//dotnet/stdlib.net:net48_system.runtime.compilerservices.unsafe.dll",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp3.1": [
                "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.dll",
                "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.xml",
            ],
        },
        net_files = {
            "net461": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net462": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net47": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net471": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net472": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net48": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netstandard2.0": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netstandard2.1": [
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
                "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
        },
        mono_files = [
            "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.dll",
            "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.xml",
        ],
    )
    nuget_package(
        name = "system.componentmodel.composition",
        package = "system.componentmodel.composition",
        version = "4.7.0",
        sha256 = "8f5ad0e2eb72a2530ddc140c48d7f7046634d202f93e9d41bbfaf225991bec11",
        core_lib = {
            "netcoreapp2.0": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netcoreapp2.1": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netcoreapp3.0": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netcoreapp3.1": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
        },
        net_lib = {
            "netstandard2.0": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netstandard2.1": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
        },
        mono_lib = "ref/netstandard2.0/System.ComponentModel.Composition.dll",
        core_files = {
            "netcoreapp2.0": [
                "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
                "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
            "netcoreapp2.1": [
                "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
                "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
            "netcoreapp3.0": [
                "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
                "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
            "netcoreapp3.1": [
                "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
                "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
        },
        net_files = {
            "netstandard2.0": [
                "lib/netstandard2.0/System.ComponentModel.Composition.dll",
                "lib/netstandard2.0/System.ComponentModel.Composition.xml",
            ],
            "netstandard2.1": [
                "lib/netstandard2.0/System.ComponentModel.Composition.dll",
                "lib/netstandard2.0/System.ComponentModel.Composition.xml",
            ],
        },
        mono_files = [
            "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
            "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
        ],
    )
    nuget_package(
        name = "microsoft.web.xdt",
        package = "microsoft.web.xdt",
        version = "3.0.0",
        sha256 = "161152cd56e0b6d602b6ba9470854537654a184cf52790c8f08cd107817371a1",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
        },
        net_lib = {
            "net45": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net451": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net452": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net46": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net461": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net462": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net47": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net471": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net472": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net48": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
        },
        mono_lib = "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netcoreapp3.1": [
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
        },
        net_files = {
            "net45": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net451": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net452": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net46": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net461": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net462": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net47": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net471": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net472": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net48": [
                "lib/net40/Microsoft.Web.XmlTransform.dll",
                "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "netstandard2.0": [
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netstandard2.1": [
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
                "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
        },
        mono_files = [
            "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
        ],
    )
    nuget_package(
        name = "microsoft.dotnet.internalabstractions",
        package = "microsoft.dotnet.internalabstractions",
        version = "1.0.0",
        sha256 = "1d7de23971fbe48d4bede3628426cc3430e9728b5f6697d051da9d45318ce856",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netcoreapp2.1": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netcoreapp3.0": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netcoreapp3.1": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
        },
        net_lib = {
            "net451": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net452": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net46": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net461": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net462": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net47": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net471": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net472": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net48": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.3": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.4": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.5": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.6": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard2.0": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard2.1": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
        },
        mono_lib = "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
        mono_deps = [
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.appcontext.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.collections.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.io.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.io.filesystem.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.reflection.typeextensions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.extensions.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.interopservices.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib:system.runtime.interopservices.runtimeinformation.dll",
        ],
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netcoreapp2.1": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netcoreapp3.0": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netcoreapp3.1": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
        },
        net_files = {
            "net451": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net452": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net46": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net461": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net462": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net47": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net471": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net472": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net48": [
                "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.3": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.4": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.5": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.6": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard2.0": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard2.1": [
                "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
        },
        mono_files = [
            "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
        ],
    )
    ### End of generated by the tool
