load("@io_bazel_rules_dotnet//dotnet/private:rules/nuget.bzl", "nuget_package")

def repositories_nugets():
    ### Generated by the tool
    nuget_package(
        name = "microsoft.extensions.filesystemglobbing",
        package = "microsoft.extensions.filesystemglobbing",
        version = "3.1.3",
        sha256 = "15ff566cbf79a964269711cb4b1000187ce9bd18a5292363ca55d00ff91a28a5",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
        },
        net_lib = {
            "net461": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net462": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net47": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net471": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net472": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "net48": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
        },
        mono_lib = "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
        },
        net_files = {
            "net461": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net462": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net47": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net471": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net472": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "net48": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netstandard2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
               "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
            ],
        },
        mono_files = [
            "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll",
            "lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.xml",
        ],
    )
    nuget_package(
        name = "newtonsoft.json",
        package = "newtonsoft.json",
        version = "9.0.1",
        sha256 = "998081ae052120917346e2cb57d488888147a2fcdf47c52ea9f83a7b4f049e55",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netcoreapp2.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netcoreapp3.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netcoreapp3.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
        },
        net_lib = {
            "net45": "lib/net45/Newtonsoft.Json.dll",
            "net451": "lib/net45/Newtonsoft.Json.dll",
            "net452": "lib/net45/Newtonsoft.Json.dll",
            "net46": "lib/net45/Newtonsoft.Json.dll",
            "net461": "lib/net45/Newtonsoft.Json.dll",
            "net462": "lib/net45/Newtonsoft.Json.dll",
            "net47": "lib/net45/Newtonsoft.Json.dll",
            "net471": "lib/net45/Newtonsoft.Json.dll",
            "net472": "lib/net45/Newtonsoft.Json.dll",
            "net48": "lib/net45/Newtonsoft.Json.dll",
            "netstandard1.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.2": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.3": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.4": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.5": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard1.6": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard2.0": "lib/netstandard1.0/Newtonsoft.Json.dll",
            "netstandard2.1": "lib/netstandard1.0/Newtonsoft.Json.dll",
        },
        mono_lib = "lib/net45/Newtonsoft.Json.dll",
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netcoreapp2.1": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netcoreapp3.0": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netcoreapp3.1": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
        },
        net_files = {
            "net45": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net451": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net452": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net46": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net461": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net462": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net47": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net471": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net472": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "net48": [
               "lib/net45/Newtonsoft.Json.dll",
               "lib/net45/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.0": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.1": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.2": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.3": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.4": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.5": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard1.6": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard2.0": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
            "netstandard2.1": [
               "lib/netstandard1.0/Newtonsoft.Json.dll",
               "lib/netstandard1.0/Newtonsoft.Json.xml",
               "tools/install.ps1",
            ],
        },
        mono_files = [
            "lib/net45/Newtonsoft.Json.dll",
            "lib/net45/Newtonsoft.Json.xml",
            "tools/install.ps1",
        ],
    )
    nuget_package(
        name = "system.runtime.interopservices.runtimeinformation",
        package = "system.runtime.interopservices.runtimeinformation",
        version = "4.0.0",
        sha256 = "e63e776a66fbe80dd23e21370749654f65cfc74e7cf82804ece5cbe1b2da953e",
        core_ref = {
            "netcoreapp2.0": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netcoreapp2.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netcoreapp3.0": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netcoreapp3.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
        },
        net_lib = {
            "net45": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net451": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net452": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net46": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net461": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net462": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net47": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net471": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net472": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net48": "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
        },
        net_ref = {
            "net45": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net451": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net452": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net46": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net461": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net462": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net47": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net471": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net472": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "net48": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.2": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.3": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.4": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.5": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard1.6": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard2.0": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
            "netstandard2.1": "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
        },
        mono_lib = "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
        mono_ref = "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll",
        net_files = {
            "net45": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net451": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net452": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net46": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net461": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net462": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net47": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net471": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net472": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
            "net48": [
               "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
            ],
        },
        mono_files = [
            "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll",
        ],
    )
    nuget_package(
        name = "microsoft.extensions.dependencymodel",
        package = "microsoft.extensions.dependencymodel",
        version = "3.1.3",
        sha256 = "e2ef26cd9c49f82084e9c8a64082478253fad280fa0c736af4cb94bf5315d428",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
        },
        net_lib = {
            "net451": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net452": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net46": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net461": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net462": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net47": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net471": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net472": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "net48": "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.3": "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.4": "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.5": "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
            "netstandard1.6": "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
        },
        mono_lib = "lib/net451/Microsoft.Extensions.DependencyModel.dll",
        net_deps = {
            "net451": [
               "@newtonsoft.json//:net451_net",
               "@system.runtime.interopservices.runtimeinformation//:net451_net",
            ],
            "net452": [
               "@newtonsoft.json//:net452_net",
               "@system.runtime.interopservices.runtimeinformation//:net452_net",
            ],
            "net46": [
               "@newtonsoft.json//:net46_net",
               "@system.runtime.interopservices.runtimeinformation//:net46_net",
            ],
            "net461": [
               "@newtonsoft.json//:net461_net",
               "@system.runtime.interopservices.runtimeinformation//:net461_net",
            ],
            "net462": [
               "@newtonsoft.json//:net462_net",
               "@system.runtime.interopservices.runtimeinformation//:net462_net",
            ],
            "net47": [
               "@newtonsoft.json//:net47_net",
               "@system.runtime.interopservices.runtimeinformation//:net47_net",
            ],
            "net471": [
               "@newtonsoft.json//:net471_net",
               "@system.runtime.interopservices.runtimeinformation//:net471_net",
            ],
            "net472": [
               "@newtonsoft.json//:net472_net",
               "@system.runtime.interopservices.runtimeinformation//:net472_net",
            ],
            "net48": [
               "@newtonsoft.json//:net48_net",
               "@system.runtime.interopservices.runtimeinformation//:net48_net",
            ],
            "netstandard1.3": [
               "@newtonsoft.json//:netstandard1.3_net",
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.3_net",
            ],
            "netstandard1.4": [
               "@newtonsoft.json//:netstandard1.4_net",
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.4_net",
            ],
            "netstandard1.5": [
               "@newtonsoft.json//:netstandard1.5_net",
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.5_net",
            ],
            "netstandard1.6": [
               "@newtonsoft.json//:netstandard1.6_net",
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.6_net",
            ],
        },
        mono_deps = [
            "@newtonsoft.json//:mono",
            "@system.runtime.interopservices.runtimeinformation//:mono",
        ],
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
        },
        net_files = {
            "net451": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net452": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net46": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net461": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net462": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net47": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net471": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net472": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "net48": [
               "lib/net451/Microsoft.Extensions.DependencyModel.dll",
               "lib/net451/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.3": [
               "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.4": [
               "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.5": [
               "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard1.6": [
               "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml",
            ],
        },
        mono_files = [
            "lib/net451/Microsoft.Extensions.DependencyModel.dll",
            "lib/net451/Microsoft.Extensions.DependencyModel.xml",
        ],
    )
    nuget_package(
        name = "microsoft.extensions.primitives",
        package = "microsoft.extensions.primitives",
        version = "3.1.3",
        sha256 = "7b77cdb2f39328637eb66bf0982c07badc01c655c9f14e7185cc494b455d154b",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp3.1": "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.dll",
        },
        net_lib = {
            "net461": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net462": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net47": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net471": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net472": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "net48": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
        },
        mono_lib = "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
        mono_deps = [
            "@system.memory//:mono",
            "@system.runtime.compilerservices.unsafe//:mono",
        ],
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.dll",
               "lib/netcoreapp3.1/Microsoft.Extensions.Primitives.xml",
            ],
        },
        net_files = {
            "net461": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net462": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net47": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net471": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net472": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "net48": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netstandard2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
        },
        mono_files = [
            "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
        ],
    )
    nuget_package(
        name = "system.componentmodel.composition",
        package = "system.componentmodel.composition",
        version = "4.7.0",
        sha256 = "8f5ad0e2eb72a2530ddc140c48d7f7046634d202f93e9d41bbfaf225991bec11",
        core_lib = {
            "netcoreapp2.0": "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
            "netcoreapp2.1": "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
            "netcoreapp3.0": "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
            "netcoreapp3.1": "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
        },
        core_ref = {
            "netcoreapp2.0": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netcoreapp2.1": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netcoreapp3.0": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netcoreapp3.1": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
        },
        net_lib = {
            "netstandard2.0": "lib/netstandard2.0/System.ComponentModel.Composition.dll",
            "netstandard2.1": "lib/netstandard2.0/System.ComponentModel.Composition.dll",
        },
        net_ref = {
            "netstandard2.0": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
            "netstandard2.1": "ref/netstandard2.0/System.ComponentModel.Composition.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
               "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
            "netcoreapp2.1": [
               "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
               "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
               "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp2.0/System.ComponentModel.Composition.dll",
               "lib/netcoreapp2.0/System.ComponentModel.Composition.xml",
            ],
        },
        net_files = {
            "netstandard2.0": [
               "lib/netstandard2.0/System.ComponentModel.Composition.dll",
               "lib/netstandard2.0/System.ComponentModel.Composition.xml",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/System.ComponentModel.Composition.dll",
               "lib/netstandard2.0/System.ComponentModel.Composition.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.web.xdt",
        package = "microsoft.web.xdt",
        version = "3.0.0",
        sha256 = "161152cd56e0b6d602b6ba9470854537654a184cf52790c8f08cd107817371a1",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
        },
        net_lib = {
            "net45": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net451": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net452": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net46": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net461": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net462": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net47": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net471": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net472": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "net48": "lib/net40/Microsoft.Web.XmlTransform.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
        },
        mono_lib = "lib/net40/Microsoft.Web.XmlTransform.dll",
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
        },
        net_files = {
            "net45": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net451": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net452": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net46": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net461": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net462": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net47": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net471": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net472": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "net48": [
               "lib/net40/Microsoft.Web.XmlTransform.dll",
               "lib/net40/Microsoft.Web.XmlTransform.pdb",
            ],
            "netstandard2.0": [
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.dll",
               "lib/netstandard2.0/Microsoft.Web.XmlTransform.pdb",
            ],
        },
        mono_files = [
            "lib/net40/Microsoft.Web.XmlTransform.dll",
            "lib/net40/Microsoft.Web.XmlTransform.pdb",
        ],
    )
    nuget_package(
        name = "microsoft.dotnet.internalabstractions",
        package = "microsoft.dotnet.internalabstractions",
        version = "1.0.0",
        sha256 = "1d7de23971fbe48d4bede3628426cc3430e9728b5f6697d051da9d45318ce856",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netcoreapp2.1": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netcoreapp3.0": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netcoreapp3.1": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
        },
        net_lib = {
            "net451": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net452": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net46": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net461": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net462": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net47": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net471": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net472": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "net48": "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.3": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.4": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.5": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard1.6": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard2.0": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            "netstandard2.1": "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
        },
        mono_lib = "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
        core_deps = {
            "netcoreapp2.0": [
               "@system.runtime.interopservices.runtimeinformation//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@system.runtime.interopservices.runtimeinformation//:netcoreapp2.1_core",
            ],
            "netcoreapp3.0": [
               "@system.runtime.interopservices.runtimeinformation//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@system.runtime.interopservices.runtimeinformation//:netcoreapp3.1_core",
            ],
        },
        net_deps = {
            "netstandard1.3": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.3_net",
            ],
            "netstandard1.4": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.4_net",
            ],
            "netstandard1.5": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.5_net",
            ],
            "netstandard1.6": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.6_net",
            ],
            "netstandard2.0": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard2.0_net",
            ],
            "netstandard2.1": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard2.1_net",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netcoreapp2.1": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netcoreapp3.0": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netcoreapp3.1": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
        },
        net_files = {
            "net451": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net452": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net46": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net461": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net462": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net47": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net471": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net472": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "net48": [
               "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.3": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.4": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.5": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard1.6": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard2.0": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
            "netstandard2.1": [
               "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
            ],
        },
        mono_files = [
            "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
        ],
    )
    nuget_package(
        name = "microsoft.dotnet.platformabstractions",
        package = "microsoft.dotnet.platformabstractions",
        version = "3.1.3",
        sha256 = "5f9cdf209694bfe719b7c6fbc130c47743f2fd98cc8c81901a2667311137414d",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
        },
        net_lib = {
            "net45": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net451": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net452": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net46": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net461": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net462": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net47": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net471": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net472": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "net48": "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "netstandard1.3": "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
            "netstandard1.4": "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
            "netstandard1.5": "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
            "netstandard1.6": "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
            "netstandard2.0": "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
            "netstandard2.1": "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
        },
        mono_lib = "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
        net_deps = {
            "net45": [
               "@system.runtime.interopservices.runtimeinformation//:net45_net",
            ],
            "net451": [
               "@system.runtime.interopservices.runtimeinformation//:net451_net",
            ],
            "net452": [
               "@system.runtime.interopservices.runtimeinformation//:net452_net",
            ],
            "net46": [
               "@system.runtime.interopservices.runtimeinformation//:net46_net",
            ],
            "net461": [
               "@system.runtime.interopservices.runtimeinformation//:net461_net",
            ],
            "net462": [
               "@system.runtime.interopservices.runtimeinformation//:net462_net",
            ],
            "net47": [
               "@system.runtime.interopservices.runtimeinformation//:net47_net",
            ],
            "net471": [
               "@system.runtime.interopservices.runtimeinformation//:net471_net",
            ],
            "net472": [
               "@system.runtime.interopservices.runtimeinformation//:net472_net",
            ],
            "net48": [
               "@system.runtime.interopservices.runtimeinformation//:net48_net",
            ],
            "netstandard1.3": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.3_net",
            ],
            "netstandard1.4": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.4_net",
            ],
            "netstandard1.5": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.5_net",
            ],
            "netstandard1.6": [
               "@system.runtime.interopservices.runtimeinformation//:netstandard1.6_net",
            ],
        },
        mono_deps = [
            "@system.runtime.interopservices.runtimeinformation//:mono",
        ],
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
        },
        net_files = {
            "net45": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net451": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net452": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net46": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net461": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net462": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net47": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net471": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net472": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "net48": [
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netstandard1.3": [
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netstandard1.4": [
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netstandard1.5": [
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netstandard1.6": [
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netstandard2.0": [
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll",
               "lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.xml",
            ],
        },
        mono_files = [
            "lib/net45/Microsoft.DotNet.PlatformAbstractions.dll",
            "lib/net45/Microsoft.DotNet.PlatformAbstractions.xml",
        ],
    )
    nuget_package(
        name = "system.security.cryptography.protecteddata",
        package = "system.security.cryptography.protecteddata",
        version = "4.5.0",
        sha256 = "67e5f5676944acb2fb627b768c5b3392eebf220ae780edd5d5b49f6530621487",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netcoreapp2.1": "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netcoreapp3.0": "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netcoreapp3.1": "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
        },
        core_ref = {
            "netcoreapp2.0": "ref/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netcoreapp2.1": "ref/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netcoreapp3.0": "ref/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netcoreapp3.1": "ref/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
        },
        net_lib = {
            "net46": "lib/net46/System.Security.Cryptography.ProtectedData.dll",
            "net461": "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            "net462": "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            "net47": "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            "net471": "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            "net472": "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            "net48": "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.3": "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.4": "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.5": "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.6": "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard2.0": "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netstandard2.1": "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
        },
        net_ref = {
            "net46": "ref/net46/System.Security.Cryptography.ProtectedData.dll",
            "net461": "ref/net461/System.Security.Cryptography.ProtectedData.dll",
            "net462": "ref/net461/System.Security.Cryptography.ProtectedData.dll",
            "net47": "ref/net461/System.Security.Cryptography.ProtectedData.dll",
            "net471": "ref/net461/System.Security.Cryptography.ProtectedData.dll",
            "net472": "ref/net461/System.Security.Cryptography.ProtectedData.dll",
            "net48": "ref/net461/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.3": "ref/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.4": "ref/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.5": "ref/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard1.6": "ref/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            "netstandard2.0": "ref/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            "netstandard2.1": "ref/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
        },
        mono_lib = "lib/net461/System.Security.Cryptography.ProtectedData.dll",
        mono_ref = "ref/net461/System.Security.Cryptography.ProtectedData.dll",
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            ],
        },
        net_files = {
            "net46": [
               "lib/net46/System.Security.Cryptography.ProtectedData.dll",
            ],
            "net461": [
               "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            ],
            "net462": [
               "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            ],
            "net47": [
               "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            ],
            "net471": [
               "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            ],
            "net472": [
               "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            ],
            "net48": [
               "lib/net461/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netstandard1.3": [
               "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netstandard1.4": [
               "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netstandard1.5": [
               "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netstandard1.6": [
               "lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netstandard2.0": [
               "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            ],
            "netstandard2.1": [
               "lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll",
            ],
        },
        mono_files = [
            "lib/net461/System.Security.Cryptography.ProtectedData.dll",
        ],
    )
    ### End of generated by the tool
    return