workspace(name = "rules_dotnet_3rd_party")

local_repository(
    name = "io_bazel_rules_dotnet",
    path = "/Users/tomek/rules_dotnet",
#    path = "c:/rules_dotnet",
)

#git_repository(
#    name = "io_bazel_rules_dotnet",
#    remote = "https://github.com/bazelbuild/rules_dotnet.git",
#    commit = "229f507dc2fb1b1ed685a6cfe03ade24a9797fa3",
#)

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories", "nuget_package")

dotnet_repositories()
dotnet_register_toolchains("host")

new_http_archive(
    name = "xunit_abstractions",
    build_file = "//:abstractions.xunit/repo.bzl",
    urls = ["https://github.com/xunit/abstractions.xunit/archive/2.0.1.tar.gz"]
)

new_http_archive(
    name = "xunit_assert",
    build_file = "//:assert.xunit/repo.bzl",
    urls = ["https://github.com/xunit/assert.xunit/archive/2.4.1.tar.gz"],
    strip_prefix="assert.xunit-2.4.1",
)


### Generated by the tool
nuget_package(
   name = "system.xml.xpath.xmldocument",
   package = "system.xml.xpath.xmldocument",
   version = "4.3.0",
   sha256 = "",
   core_lib = "ref/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   net_lib = "ref/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   mono_lib = "ref/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.collections.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.globalization.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.resources.resourcemanager.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.extensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.threading.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.readerwriter.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xmldocument.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xpath.dll",
   ],
   net_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xmldocument.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xpath.dll",
   ],
   mono_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xmldocument.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xpath.dll",
   ],
   core_files = [
       "lib/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   ],
   net_files = [
       "lib/net46/System.Xml.XPath.XmlDocument.dll",
   ],
   mono_files = [
       "lib/net46/System.Xml.XPath.XmlDocument.dll",
   ],
)
nuget_package(
   name = "microsoft.testplatform.objectmodel",
   package = "microsoft.testplatform.objectmodel",
   version = "15.0.0",
   sha256 = "",
   core_lib = "lib/netstandard1.5/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
   net_lib = "lib/net46/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
   mono_lib = "lib/net46/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:netstandard.library.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.serialization.primitives.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.extensions.dll",
       "@system.xml.xpath.xmldocument//:core",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.componentmodel.eventbasedasync.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.filesystem.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.componentmodel.typeconverter.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.security.cryptography.algorithms.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.serialization.json.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.runtimeinformation.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.loader.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.reflection.typeextensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.reflection.metadata.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.diagnostics.tracing.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.diagnostics.process.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.diagnostics.tracesource.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.threading.thread.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.diagnostics.textwritertracelistener.dll",
   ],
   net_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.runtimeinformation.dll",
   ],
   mono_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.runtimeinformation.dll",
   ],
   core_files = [
       "lib/netstandard1.5/cs/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/cs/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/de/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/de/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/es/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/es/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/fr/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/fr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/it/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/it/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/ja/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/ja/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/ko/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/ko/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/Microsoft.TestPlatform.CoreUtilities.dll",
       "lib/netstandard1.5/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
       "lib/netstandard1.5/pl/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/pl/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/ru/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/ru/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/tr/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/tr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/zh-Hans/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/zh-Hans/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/netstandard1.5/zh-Hant/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/netstandard1.5/zh-Hant/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
   ],
   net_files = [
       "lib/net46/cs/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/cs/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/de/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/de/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/es/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/es/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/fr/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/fr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/it/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/it/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/ja/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/ja/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/ko/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/ko/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/Microsoft.TestPlatform.CoreUtilities.dll",
       "lib/net46/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
       "lib/net46/pl/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/pl/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/ru/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/ru/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/tr/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/tr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/zh-Hans/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/zh-Hans/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/zh-Hant/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/zh-Hant/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
   ],
   mono_files = [
       "lib/net46/cs/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/cs/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/de/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/de/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/es/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/es/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/fr/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/fr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/it/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/it/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/ja/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/ja/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/ko/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/ko/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/Microsoft.TestPlatform.CoreUtilities.dll",
       "lib/net46/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
       "lib/net46/pl/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/pl/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/ru/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/ru/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/tr/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/tr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/zh-Hans/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/zh-Hans/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
       "lib/net46/zh-Hant/Microsoft.TestPlatform.CoreUtilities.resources.dll",
       "lib/net46/zh-Hant/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll",
   ],
)
nuget_package(
   name = "microsoft.dotnet.internalabstractions",
   package = "microsoft.dotnet.internalabstractions",
   version = "1.0.0",
   core_lib = "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
   net_lib = "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   mono_lib = "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.appcontext.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.collections.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.filesystem.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.reflection.typeextensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.extensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.runtimeinformation.dll",
   ],
   core_files = [
       "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
   ],
   net_files = [
       "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   ],
   mono_files = [
       "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   ],
)
### End of generated by the tool
