workspace(name = "rules_dotnet_3rd_party")

local_repository(
    name = "io_bazel_rules_dotnet",
#    path = "/Users/tomek/rules_dotnet",
    path = "c:/rules_dotnet",
)

#git_repository(
#    name = "io_bazel_rules_dotnet",
#    remote = "https://github.com/bazelbuild/rules_dotnet.git",
#    commit = "229f507dc2fb1b1ed685a6cfe03ade24a9797fa3",
#)

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories", "nuget_package")

dotnet_repositories()
dotnet_register_toolchains("host")

new_http_archive(
    name = "xunit_abstractions",
    build_file = "//:abstractions.xunit/repo.bzl",
    urls = ["https://github.com/xunit/abstractions.xunit/archive/2.0.1.tar.gz"]
)

new_http_archive(
    name = "xunit_assert",
    build_file = "//:assert.xunit/repo.bzl",
    urls = ["https://github.com/xunit/assert.xunit/archive/2.4.1.tar.gz"],
    strip_prefix="assert.xunit-2.4.1",
)


### Generated by the tool
nuget_package(
   name = "system.xml.xpath.xmldocument",
   package = "system.xml.xpath.xmldocument",
   version = "4.3.0",
   sha256 = "",
   core_lib = "ref/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   net_lib = "ref/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   mono_lib = "ref/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.collections.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.globalization.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.resources.resourcemanager.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.extensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.threading.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.readerwriter.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xmldocument.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xpath.dll",
   ],
   net_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xmldocument.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xpath.dll",
   ],
   mono_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xmldocument.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.xml.xpath.dll",
   ],
   core_files = [
       "lib/netstandard1.3/System.Xml.XPath.XmlDocument.dll",
   ],
   net_files = [
       "lib/net46/System.Xml.XPath.XmlDocument.dll",
   ],
   mono_files = [
       "lib/net46/System.Xml.XPath.XmlDocument.dll",
   ],
)
nuget_package(
   name = "microsoft.dotnet.internalabstractions",
   package = "microsoft.dotnet.internalabstractions",
   version = "1.0.0",
   sha256 = "",
   core_lib = "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
   net_lib = "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   mono_lib = "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.appcontext.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.collections.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.filesystem.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.reflection.typeextensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.extensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.runtimeinformation.dll",
   ],
   core_files = [
       "lib/netstandard1.3/Microsoft.DotNet.InternalAbstractions.dll",
   ],
   net_files = [
       "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   ],
   mono_files = [
       "lib/net451/Microsoft.DotNet.InternalAbstractions.dll",
   ],
)
nuget_package(
   name = "microsoft.dotnet.platformabstractions",
   package = "microsoft.dotnet.platformabstractions",
   version = "1.1.9",
   core_lib = "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
   net_lib = "lib/net451/Microsoft.DotNet.PlatformAbstractions.dll",
   mono_lib = "lib/net451/Microsoft.DotNet.PlatformAbstractions.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.appcontext.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.collections.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.io.filesystem.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.reflection.typeextensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.extensions.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.runtime.interopservices.runtimeinformation.dll",
   ],
   core_files = [
       "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll",
   ],
   net_files = [
       "lib/net451/Microsoft.DotNet.PlatformAbstractions.dll",
   ],
   mono_files = [
       "lib/net451/Microsoft.DotNet.PlatformAbstractions.dll",
   ],
)
nuget_package(
   name = "microsoft.extensions.dependencymodel",
   package = "microsoft.extensions.dependencymodel",
   version = "1.0.3",
   core_lib = "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
   net_lib = "lib/net451/Microsoft.Extensions.DependencyModel.dll",
   mono_lib = "lib/net451/Microsoft.Extensions.DependencyModel.dll",
   core_deps = [
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.diagnostics.debug.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.dynamic.runtime.dll",
       "@io_bazel_rules_dotnet//dotnet/stdlib.core:system.linq.dll",
       "@microsoft.dotnet.platformabstractions//:core",
   ],
   net_deps = [
       "@microsoft.dotnet.platformabstractions//:net",
   ],
   mono_deps = [
       "@microsoft.dotnet.platformabstractions//:mono",
   ],
   core_files = [
       "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
   ],
   net_files = [
       "lib/net451/Microsoft.Extensions.DependencyModel.dll",
   ],
   mono_files = [
       "lib/net451/Microsoft.Extensions.DependencyModel.dll",
   ],
)
### End of generated by the tool
